Repository NakiNorton/book-lovers, pull requests merged in 2020-09, with the labels that each got.

#5 Add components and basic imports #3
  src/API.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/Book/Book.css
  src/Components/Book/Book.js
  src/Components/Book/Book.test.js
  src/Components/BookInfo/BookInfo.css
  src/Components/BookInfo/BookInfo.js
  src/Components/BookInfo/BookInfo.test.js
  src/Components/Books/Books.css
  src/Components/Books/Books.js
  src/Components/Books/Books.test.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.test.js
Labels: enhancement, setup

#9 Feature/ak/homepage
  src/API.js
  src/Components/App/App.js
  src/Components/Book/Book.css
  src/Components/Book/Book.js
  src/Components/BookInfo/BookInfo.js
  src/Components/Books/Books.css
  src/Components/Books/Books.js
  src/Components/Nav/Nav.js
  src/index.js
Labels: App, Book, Books, enhancement, styling

#12 Sn feature/nav component
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.test.js
  src/assets/book.png
  src/index.js
Labels: Nav, enhancement, styling, testing

#60 Bug/jkw/set list issue
  src/Components/App/App.js
  src/Components/Books/Books.js
  src/reducers/Lists.js
Labels: refactor

#56 Testing/jkw/lists redux
  src/actions/setList.test.js
  src/reducers/ListsReducer.test.js
Labels: testing
